### ISSUE TITLE
Dropdown Button for specific write ups and exit comment

### ISSUE THREAD

**Issue by Cloudy-Mushroom** [Cloudy-Mushroom/JAD#1]
The data is stored in https://github.com/Cloudy-Mushroom/JAD/blob/custom_dylan/config-files/write_ups.json

Ideally only the selected vendor options should appear, and the `outro` sections should always appear, only one should be selected

**Comment by Xiley1** [comment]
@Cloudy-Mushroom I have pushed this now so will now require backend work. You may also want to review my call on line 123 as it was required for the "intro" dropdown to appear prior to any vendor being manually selected. Not sure if this will have impact or not.

**Comment by Cloudy-Mushroom** [comment]
Yeah ngl i already deleted that line 😀 This feature now works btw so have closed it out!
