### ISSUE TITLE
CBR API and input -> output

### ISSUE THREAD

**Issue by Cloudy-Mushroom** [Cloudy-Mushroom/JAD#2]
Build the back end functionality to handle CBR API data

- [x] CBR Handler
- [x] #8
- [x] Parsing both endpoints
- [x] Extracting the specific MDR rule logic in non URL encoded format
- [x] Searching the events data and returning matching events
- [x] Pushing the relevant data to a valid cbr_mappings file

**Comment by Xiley1** [comment]
Converting to .grid has solved these 2 issues.

**Comment by Cloudy-Mushroom** [comment]
Right there were several issues with the CBR API that I have now fixed. The last few things are getting it to find the specific events in a specific feed.

**Comment by Cloudy-Mushroom** [comment]
Closing this now as CBR should be fully integrated
